version: "3.3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1"
      - "FAKETIME_NO_CACHE=1"
    volumes:
      - ./logs:/var/log/logger
    networks:
      - default
